[package]
name = "parolrs"
version = "0.1.1"
authors = ["Ogromny <ogromny@openmailbox.org>"]

[[bin]]
name = "main"
doc = false

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
sodiumoxide = "*"